// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// UserHandler is an autogenerated mock type for the UserHandler type
type UserHandler struct {
	mock.Mock
}

// ForgotPassword provides a mock function with given fields: c
func (_m *UserHandler) ForgotPassword(c *gin.Context) {
	_m.Called(c)
}

// GetUserById provides a mock function with given fields: c
func (_m *UserHandler) GetUserById(c *gin.Context) {
	_m.Called(c)
}

// LoginUser provides a mock function with given fields: c
func (_m *UserHandler) LoginUser(c *gin.Context) {
	_m.Called(c)
}

// RegisterUser provides a mock function with given fields: c
func (_m *UserHandler) RegisterUser(c *gin.Context) {
	_m.Called(c)
}

// ResetPassword provides a mock function with given fields: c
func (_m *UserHandler) ResetPassword(c *gin.Context) {
	_m.Called(c)
}

type mockConstructorTestingTNewUserHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserHandler creates a new instance of UserHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserHandler(t mockConstructorTestingTNewUserHandler) *UserHandler {
	mock := &UserHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
