// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/e_wallet.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
//Request Definition
type UserRegisterRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRegisterRequest) Reset()         { *m = UserRegisterRequest{} }
func (m *UserRegisterRequest) String() string { return proto.CompactTextString(m) }
func (*UserRegisterRequest) ProtoMessage()    {}
func (*UserRegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7cd1ef3b5ab5a5f, []int{0}
}

func (m *UserRegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegisterRequest.Unmarshal(m, b)
}
func (m *UserRegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegisterRequest.Marshal(b, m, deterministic)
}
func (m *UserRegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegisterRequest.Merge(m, src)
}
func (m *UserRegisterRequest) XXX_Size() int {
	return xxx_messageInfo_UserRegisterRequest.Size(m)
}
func (m *UserRegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegisterRequest proto.InternalMessageInfo

func (m *UserRegisterRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserRegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserRegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserLoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginRequest) Reset()         { *m = UserLoginRequest{} }
func (m *UserLoginRequest) String() string { return proto.CompactTextString(m) }
func (*UserLoginRequest) ProtoMessage()    {}
func (*UserLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7cd1ef3b5ab5a5f, []int{1}
}

func (m *UserLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginRequest.Unmarshal(m, b)
}
func (m *UserLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginRequest.Marshal(b, m, deterministic)
}
func (m *UserLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginRequest.Merge(m, src)
}
func (m *UserLoginRequest) XXX_Size() int {
	return xxx_messageInfo_UserLoginRequest.Size(m)
}
func (m *UserLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginRequest proto.InternalMessageInfo

func (m *UserLoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserLoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type TopupRequest struct {
	Amount               float32  `protobuf:"fixed32,1,opt,name=amount,proto3" json:"amount,omitempty"`
	SourceOfFundId       uint32   `protobuf:"varint,2,opt,name=source_of_fund_id,json=sourceOfFundId,proto3" json:"source_of_fund_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopupRequest) Reset()         { *m = TopupRequest{} }
func (m *TopupRequest) String() string { return proto.CompactTextString(m) }
func (*TopupRequest) ProtoMessage()    {}
func (*TopupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7cd1ef3b5ab5a5f, []int{2}
}

func (m *TopupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopupRequest.Unmarshal(m, b)
}
func (m *TopupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopupRequest.Marshal(b, m, deterministic)
}
func (m *TopupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopupRequest.Merge(m, src)
}
func (m *TopupRequest) XXX_Size() int {
	return xxx_messageInfo_TopupRequest.Size(m)
}
func (m *TopupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TopupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TopupRequest proto.InternalMessageInfo

func (m *TopupRequest) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *TopupRequest) GetSourceOfFundId() uint32 {
	if m != nil {
		return m.SourceOfFundId
	}
	return 0
}

type TransferRequest struct {
	ReceiverWalletId     string   `protobuf:"bytes,2,opt,name=receiver_wallet_id,json=receiverWalletId,proto3" json:"receiver_wallet_id,omitempty"`
	Amount               float32  `protobuf:"fixed32,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferRequest) Reset()         { *m = TransferRequest{} }
func (m *TransferRequest) String() string { return proto.CompactTextString(m) }
func (*TransferRequest) ProtoMessage()    {}
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7cd1ef3b5ab5a5f, []int{3}
}

func (m *TransferRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferRequest.Unmarshal(m, b)
}
func (m *TransferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferRequest.Marshal(b, m, deterministic)
}
func (m *TransferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferRequest.Merge(m, src)
}
func (m *TransferRequest) XXX_Size() int {
	return xxx_messageInfo_TransferRequest.Size(m)
}
func (m *TransferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransferRequest proto.InternalMessageInfo

func (m *TransferRequest) GetReceiverWalletId() string {
	if m != nil {
		return m.ReceiverWalletId
	}
	return ""
}

func (m *TransferRequest) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *TransferRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type ForgotPasswordRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgotPasswordRequest) Reset()         { *m = ForgotPasswordRequest{} }
func (m *ForgotPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ForgotPasswordRequest) ProtoMessage()    {}
func (*ForgotPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7cd1ef3b5ab5a5f, []int{4}
}

func (m *ForgotPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgotPasswordRequest.Unmarshal(m, b)
}
func (m *ForgotPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgotPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ForgotPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgotPasswordRequest.Merge(m, src)
}
func (m *ForgotPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ForgotPasswordRequest.Size(m)
}
func (m *ForgotPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgotPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForgotPasswordRequest proto.InternalMessageInfo

func (m *ForgotPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type PasswordResetRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	NewPassword          string   `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PasswordResetRequest) Reset()         { *m = PasswordResetRequest{} }
func (m *PasswordResetRequest) String() string { return proto.CompactTextString(m) }
func (*PasswordResetRequest) ProtoMessage()    {}
func (*PasswordResetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7cd1ef3b5ab5a5f, []int{5}
}

func (m *PasswordResetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PasswordResetRequest.Unmarshal(m, b)
}
func (m *PasswordResetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PasswordResetRequest.Marshal(b, m, deterministic)
}
func (m *PasswordResetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PasswordResetRequest.Merge(m, src)
}
func (m *PasswordResetRequest) XXX_Size() int {
	return xxx_messageInfo_PasswordResetRequest.Size(m)
}
func (m *PasswordResetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PasswordResetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PasswordResetRequest proto.InternalMessageInfo

func (m *PasswordResetRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *PasswordResetRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

func (m *PasswordResetRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ChooseRewardRequest struct {
	GameId               uint32   `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	BoxId                uint32   `protobuf:"varint,2,opt,name=box_id,json=boxId,proto3" json:"box_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChooseRewardRequest) Reset()         { *m = ChooseRewardRequest{} }
func (m *ChooseRewardRequest) String() string { return proto.CompactTextString(m) }
func (*ChooseRewardRequest) ProtoMessage()    {}
func (*ChooseRewardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7cd1ef3b5ab5a5f, []int{6}
}

func (m *ChooseRewardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChooseRewardRequest.Unmarshal(m, b)
}
func (m *ChooseRewardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChooseRewardRequest.Marshal(b, m, deterministic)
}
func (m *ChooseRewardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChooseRewardRequest.Merge(m, src)
}
func (m *ChooseRewardRequest) XXX_Size() int {
	return xxx_messageInfo_ChooseRewardRequest.Size(m)
}
func (m *ChooseRewardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChooseRewardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChooseRewardRequest proto.InternalMessageInfo

func (m *ChooseRewardRequest) GetGameId() uint32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

func (m *ChooseRewardRequest) GetBoxId() uint32 {
	if m != nil {
		return m.BoxId
	}
	return 0
}

type QueryCondition struct {
	SortedBy             string   `protobuf:"bytes,1,opt,name=sorted_by,json=sortedBy,proto3" json:"sorted_by,omitempty"`
	Sort                 string   `protobuf:"bytes,2,opt,name=sort,proto3" json:"sort,omitempty"`
	Limit                string   `protobuf:"bytes,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Page                 string   `protobuf:"bytes,4,opt,name=page,proto3" json:"page,omitempty"`
	StartDate            string   `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate              string   `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryCondition) Reset()         { *m = QueryCondition{} }
func (m *QueryCondition) String() string { return proto.CompactTextString(m) }
func (*QueryCondition) ProtoMessage()    {}
func (*QueryCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7cd1ef3b5ab5a5f, []int{7}
}

func (m *QueryCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryCondition.Unmarshal(m, b)
}
func (m *QueryCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryCondition.Marshal(b, m, deterministic)
}
func (m *QueryCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCondition.Merge(m, src)
}
func (m *QueryCondition) XXX_Size() int {
	return xxx_messageInfo_QueryCondition.Size(m)
}
func (m *QueryCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCondition.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCondition proto.InternalMessageInfo

func (m *QueryCondition) GetSortedBy() string {
	if m != nil {
		return m.SortedBy
	}
	return ""
}

func (m *QueryCondition) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *QueryCondition) GetLimit() string {
	if m != nil {
		return m.Limit
	}
	return ""
}

func (m *QueryCondition) GetPage() string {
	if m != nil {
		return m.Page
	}
	return ""
}

func (m *QueryCondition) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *QueryCondition) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7cd1ef3b5ab5a5f, []int{8}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

//*
//Response definition
type TransactionDetailResponse struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TransactionDate      string   `protobuf:"bytes,2,opt,name=transaction_date,json=transactionDate,proto3" json:"transaction_date,omitempty"`
	SenderName           string   `protobuf:"bytes,3,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	SenderWallet         string   `protobuf:"bytes,4,opt,name=sender_wallet,json=senderWallet,proto3" json:"sender_wallet,omitempty"`
	ReceipentName        string   `protobuf:"bytes,5,opt,name=receipent_name,json=receipentName,proto3" json:"receipent_name,omitempty"`
	ReceipentWallet      string   `protobuf:"bytes,6,opt,name=receipent_wallet,json=receipentWallet,proto3" json:"receipent_wallet,omitempty"`
	Description          string   `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Amount               float32  `protobuf:"fixed32,8,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionDetailResponse) Reset()         { *m = TransactionDetailResponse{} }
func (m *TransactionDetailResponse) String() string { return proto.CompactTextString(m) }
func (*TransactionDetailResponse) ProtoMessage()    {}
func (*TransactionDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7cd1ef3b5ab5a5f, []int{9}
}

func (m *TransactionDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionDetailResponse.Unmarshal(m, b)
}
func (m *TransactionDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionDetailResponse.Marshal(b, m, deterministic)
}
func (m *TransactionDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionDetailResponse.Merge(m, src)
}
func (m *TransactionDetailResponse) XXX_Size() int {
	return xxx_messageInfo_TransactionDetailResponse.Size(m)
}
func (m *TransactionDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionDetailResponse proto.InternalMessageInfo

func (m *TransactionDetailResponse) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TransactionDetailResponse) GetTransactionDate() string {
	if m != nil {
		return m.TransactionDate
	}
	return ""
}

func (m *TransactionDetailResponse) GetSenderName() string {
	if m != nil {
		return m.SenderName
	}
	return ""
}

func (m *TransactionDetailResponse) GetSenderWallet() string {
	if m != nil {
		return m.SenderWallet
	}
	return ""
}

func (m *TransactionDetailResponse) GetReceipentName() string {
	if m != nil {
		return m.ReceipentName
	}
	return ""
}

func (m *TransactionDetailResponse) GetReceipentWallet() string {
	if m != nil {
		return m.ReceipentWallet
	}
	return ""
}

func (m *TransactionDetailResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *TransactionDetailResponse) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type TransactionPaginationResponse struct {
	Page                 string                       `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Total                uint32                       `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Transactions         []*TransactionDetailResponse `protobuf:"bytes,3,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *TransactionPaginationResponse) Reset()         { *m = TransactionPaginationResponse{} }
func (m *TransactionPaginationResponse) String() string { return proto.CompactTextString(m) }
func (*TransactionPaginationResponse) ProtoMessage()    {}
func (*TransactionPaginationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7cd1ef3b5ab5a5f, []int{10}
}

func (m *TransactionPaginationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionPaginationResponse.Unmarshal(m, b)
}
func (m *TransactionPaginationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionPaginationResponse.Marshal(b, m, deterministic)
}
func (m *TransactionPaginationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionPaginationResponse.Merge(m, src)
}
func (m *TransactionPaginationResponse) XXX_Size() int {
	return xxx_messageInfo_TransactionPaginationResponse.Size(m)
}
func (m *TransactionPaginationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionPaginationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionPaginationResponse proto.InternalMessageInfo

func (m *TransactionPaginationResponse) GetPage() string {
	if m != nil {
		return m.Page
	}
	return ""
}

func (m *TransactionPaginationResponse) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *TransactionPaginationResponse) GetTransactions() []*TransactionDetailResponse {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type UserResponse struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7cd1ef3b5ab5a5f, []int{11}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type UserLoginResponse struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginResponse) Reset()         { *m = UserLoginResponse{} }
func (m *UserLoginResponse) String() string { return proto.CompactTextString(m) }
func (*UserLoginResponse) ProtoMessage()    {}
func (*UserLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7cd1ef3b5ab5a5f, []int{12}
}

func (m *UserLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginResponse.Unmarshal(m, b)
}
func (m *UserLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginResponse.Marshal(b, m, deterministic)
}
func (m *UserLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginResponse.Merge(m, src)
}
func (m *UserLoginResponse) XXX_Size() int {
	return xxx_messageInfo_UserLoginResponse.Size(m)
}
func (m *UserLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginResponse proto.InternalMessageInfo

func (m *UserLoginResponse) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserLoginResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserLoginResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserLoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UserDetail struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	WalletNumber         string   `protobuf:"bytes,4,opt,name=wallet_number,json=walletNumber,proto3" json:"wallet_number,omitempty"`
	Balance              float32  `protobuf:"fixed32,5,opt,name=balance,proto3" json:"balance,omitempty"`
	Chance               uint32   `protobuf:"varint,6,opt,name=chance,proto3" json:"chance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserDetail) Reset()         { *m = UserDetail{} }
func (m *UserDetail) String() string { return proto.CompactTextString(m) }
func (*UserDetail) ProtoMessage()    {}
func (*UserDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7cd1ef3b5ab5a5f, []int{13}
}

func (m *UserDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDetail.Unmarshal(m, b)
}
func (m *UserDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDetail.Marshal(b, m, deterministic)
}
func (m *UserDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDetail.Merge(m, src)
}
func (m *UserDetail) XXX_Size() int {
	return xxx_messageInfo_UserDetail.Size(m)
}
func (m *UserDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDetail.DiscardUnknown(m)
}

var xxx_messageInfo_UserDetail proto.InternalMessageInfo

func (m *UserDetail) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserDetail) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserDetail) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserDetail) GetWalletNumber() string {
	if m != nil {
		return m.WalletNumber
	}
	return ""
}

func (m *UserDetail) GetBalance() float32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *UserDetail) GetChance() uint32 {
	if m != nil {
		return m.Chance
	}
	return 0
}

type ForgotPasswordToken struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgotPasswordToken) Reset()         { *m = ForgotPasswordToken{} }
func (m *ForgotPasswordToken) String() string { return proto.CompactTextString(m) }
func (*ForgotPasswordToken) ProtoMessage()    {}
func (*ForgotPasswordToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_a7cd1ef3b5ab5a5f, []int{14}
}

func (m *ForgotPasswordToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgotPasswordToken.Unmarshal(m, b)
}
func (m *ForgotPasswordToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgotPasswordToken.Marshal(b, m, deterministic)
}
func (m *ForgotPasswordToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgotPasswordToken.Merge(m, src)
}
func (m *ForgotPasswordToken) XXX_Size() int {
	return xxx_messageInfo_ForgotPasswordToken.Size(m)
}
func (m *ForgotPasswordToken) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgotPasswordToken.DiscardUnknown(m)
}

var xxx_messageInfo_ForgotPasswordToken proto.InternalMessageInfo

func (m *ForgotPasswordToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*UserRegisterRequest)(nil), "e_wallet.UserRegisterRequest")
	proto.RegisterType((*UserLoginRequest)(nil), "e_wallet.UserLoginRequest")
	proto.RegisterType((*TopupRequest)(nil), "e_wallet.TopupRequest")
	proto.RegisterType((*TransferRequest)(nil), "e_wallet.TransferRequest")
	proto.RegisterType((*ForgotPasswordRequest)(nil), "e_wallet.ForgotPasswordRequest")
	proto.RegisterType((*PasswordResetRequest)(nil), "e_wallet.PasswordResetRequest")
	proto.RegisterType((*ChooseRewardRequest)(nil), "e_wallet.ChooseRewardRequest")
	proto.RegisterType((*QueryCondition)(nil), "e_wallet.QueryCondition")
	proto.RegisterType((*Empty)(nil), "e_wallet.Empty")
	proto.RegisterType((*TransactionDetailResponse)(nil), "e_wallet.TransactionDetailResponse")
	proto.RegisterType((*TransactionPaginationResponse)(nil), "e_wallet.TransactionPaginationResponse")
	proto.RegisterType((*UserResponse)(nil), "e_wallet.UserResponse")
	proto.RegisterType((*UserLoginResponse)(nil), "e_wallet.UserLoginResponse")
	proto.RegisterType((*UserDetail)(nil), "e_wallet.UserDetail")
	proto.RegisterType((*ForgotPasswordToken)(nil), "e_wallet.ForgotPasswordToken")
}

func init() {
	proto.RegisterFile("proto/e_wallet.proto", fileDescriptor_a7cd1ef3b5ab5a5f)
}

var fileDescriptor_a7cd1ef3b5ab5a5f = []byte{
	// 874 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xdb, 0x6e, 0x1b, 0x37,
	0x10, 0xc5, 0xae, 0x6c, 0x5d, 0x46, 0x17, 0x3b, 0xb4, 0xe3, 0x4a, 0x0a, 0xdc, 0xb8, 0x6b, 0x14,
	0x8d, 0xd1, 0xd6, 0x01, 0xdc, 0x2f, 0x68, 0x6c, 0xc7, 0x35, 0x50, 0xa4, 0xce, 0xd6, 0x41, 0x81,
	0x06, 0xa8, 0x40, 0xed, 0x8e, 0x94, 0x45, 0x57, 0xe4, 0x96, 0xa4, 0xa2, 0xe8, 0x37, 0xfa, 0xde,
	0xc7, 0x02, 0xf9, 0x81, 0xfe, 0x5f, 0x41, 0x72, 0x2f, 0x94, 0x22, 0x05, 0x01, 0xf2, 0x24, 0xce,
	0x85, 0x67, 0x67, 0x86, 0x67, 0x66, 0x04, 0x87, 0x99, 0xe0, 0x8a, 0x3f, 0xc5, 0xd1, 0x82, 0xa6,
	0x29, 0xaa, 0x73, 0x23, 0x92, 0x66, 0x21, 0x07, 0xaf, 0xe1, 0xe0, 0x95, 0x44, 0x11, 0xe2, 0x34,
	0x91, 0x4a, 0xff, 0xfe, 0x35, 0x47, 0xa9, 0x08, 0x81, 0x1d, 0x46, 0x67, 0xd8, 0xf7, 0x4e, 0xbc,
	0x27, 0xad, 0xd0, 0x9c, 0xc9, 0x21, 0xec, 0xe2, 0x8c, 0x26, 0x69, 0xdf, 0x37, 0x4a, 0x2b, 0x90,
	0x21, 0x34, 0x33, 0x2a, 0xe5, 0x82, 0x8b, 0xb8, 0x5f, 0x33, 0x86, 0x52, 0x0e, 0xae, 0x60, 0x5f,
	0x83, 0xff, 0xcc, 0xa7, 0x09, 0x2b, 0x90, 0x4b, 0x14, 0x6f, 0x1b, 0x8a, 0xbf, 0x86, 0xf2, 0x12,
	0x3a, 0xf7, 0x3c, 0x9b, 0x67, 0x05, 0xc2, 0x11, 0xd4, 0xe9, 0x8c, 0xcf, 0x99, 0x32, 0x10, 0x7e,
	0x98, 0x4b, 0xe4, 0x0c, 0x1e, 0x48, 0x3e, 0x17, 0x11, 0x8e, 0xf8, 0x64, 0x34, 0x99, 0xb3, 0x78,
	0x94, 0x58, 0xb0, 0x6e, 0xd8, 0xb3, 0x86, 0x5f, 0x26, 0xcf, 0xe7, 0x2c, 0xbe, 0x8d, 0x83, 0x25,
	0xec, 0xdd, 0x0b, 0xca, 0xe4, 0xa4, 0xca, 0xf8, 0x3b, 0x20, 0x02, 0x23, 0x4c, 0xde, 0xa2, 0xc8,
	0x6b, 0x53, 0x5c, 0x6f, 0x85, 0xfb, 0x85, 0xe5, 0x37, 0x63, 0xb8, 0x8d, 0x9d, 0x18, 0x6a, 0x2b,
	0x31, 0x9c, 0x40, 0x3b, 0x46, 0x19, 0x89, 0x24, 0x53, 0x09, 0x67, 0xfd, 0x1d, 0x73, 0xdd, 0x55,
	0x05, 0xdf, 0xc3, 0xc3, 0xe7, 0x5c, 0x4c, 0xb9, 0xba, 0xcb, 0xf3, 0xfb, 0x68, 0x61, 0x02, 0x84,
	0xc3, 0xca, 0x51, 0xa2, 0xfa, 0x78, 0x19, 0xbf, 0x82, 0x0e, 0xc3, 0xc5, 0x68, 0xad, 0x94, 0x6d,
	0x86, 0x8b, 0x02, 0x44, 0x5f, 0x54, 0xfc, 0x4f, 0x64, 0xf9, 0x63, 0x59, 0x21, 0xb8, 0x86, 0x83,
	0xcb, 0x37, 0x9c, 0x4b, 0x0c, 0x71, 0x41, 0xab, 0x98, 0xbe, 0x80, 0xc6, 0x94, 0xce, 0x50, 0x57,
	0xc2, 0x33, 0x85, 0xac, 0x6b, 0xf1, 0x36, 0x26, 0x0f, 0xa1, 0x3e, 0xe6, 0xef, 0xaa, 0x02, 0xef,
	0x8e, 0xf9, 0xbb, 0xdb, 0x38, 0xf8, 0xd7, 0x83, 0xde, 0xcb, 0x39, 0x8a, 0xe5, 0x25, 0x67, 0x71,
	0xa2, 0xf3, 0x25, 0x8f, 0xa0, 0x25, 0xb9, 0x50, 0x18, 0x8f, 0xc6, 0xcb, 0x3c, 0xd8, 0xa6, 0x55,
	0x3c, 0x5b, 0x6a, 0x9a, 0xe9, 0x73, 0x1e, 0xa7, 0x39, 0xeb, 0x00, 0xd3, 0x64, 0x96, 0xa8, 0x22,
	0x40, 0x23, 0x68, 0xcf, 0x8c, 0x4e, 0x31, 0xaf, 0xa8, 0x39, 0x93, 0x63, 0x00, 0xa9, 0xa8, 0x50,
	0xa3, 0x98, 0x2a, 0xec, 0xef, 0x1a, 0x4b, 0xcb, 0x68, 0xae, 0xa8, 0x42, 0x32, 0x80, 0x26, 0xb2,
	0xd8, 0x1a, 0xeb, 0xc6, 0xd8, 0x40, 0x16, 0x6b, 0x53, 0xd0, 0x80, 0xdd, 0xeb, 0x59, 0xa6, 0x96,
	0xc1, 0x7b, 0x1f, 0x06, 0x86, 0x09, 0x34, 0xd2, 0xd1, 0x5e, 0xa1, 0xa2, 0x49, 0x1a, 0xa2, 0xcc,
	0x38, 0x93, 0x48, 0x7a, 0xe0, 0x97, 0x99, 0xfb, 0x49, 0x4c, 0xce, 0x60, 0x5f, 0x55, 0xce, 0x16,
	0xd9, 0x86, 0xbe, 0xe7, 0xe8, 0xcd, 0xc7, 0x1f, 0x43, 0x5b, 0x22, 0x8b, 0x51, 0x8c, 0x4c, 0x1f,
	0xd9, 0x5c, 0xc0, 0xaa, 0x5e, 0xe8, 0x6e, 0x3a, 0x85, 0x6e, 0xee, 0x60, 0xd9, 0x96, 0x67, 0xd6,
	0xb1, 0x4a, 0x4b, 0x34, 0xf2, 0x35, 0xf4, 0x0c, 0xf5, 0x32, 0x64, 0xca, 0x02, 0xd9, 0x2c, 0xbb,
	0xa5, 0xd6, 0x60, 0x9d, 0xc1, 0x7e, 0xe5, 0x96, 0xc3, 0xd9, 0x8c, 0xf7, 0x4a, 0x7d, 0x8e, 0xb8,
	0x46, 0xd0, 0xc6, 0x07, 0x04, 0x75, 0xa8, 0xdd, 0x74, 0xa9, 0x1d, 0xfc, 0xed, 0xc1, 0xb1, 0x53,
	0xaa, 0x3b, 0x3a, 0x4d, 0x18, 0xd5, 0xa7, 0xb2, 0x5c, 0xc5, 0x1b, 0x79, 0xce, 0x1b, 0x19, 0xba,
	0x29, 0x9a, 0x16, 0x3c, 0x31, 0x02, 0xb9, 0x81, 0x8e, 0x53, 0x30, 0xd9, 0xaf, 0x9d, 0xd4, 0x9e,
	0xb4, 0x2f, 0x4e, 0xcf, 0xcb, 0x31, 0xb5, 0xf5, 0x4d, 0xc2, 0x95, 0x8b, 0xc1, 0x4f, 0xd0, 0xb1,
	0xe3, 0x6b, 0xcb, 0x8b, 0x15, 0x73, 0xcc, 0xdf, 0x34, 0xc7, 0x6a, 0x6e, 0xa3, 0x45, 0xf0, 0xc0,
	0x99, 0x55, 0x9f, 0x0b, 0x57, 0xb5, 0xd9, 0x8e, 0xdb, 0x66, 0xff, 0x78, 0x00, 0xfa, 0x2b, 0x36,
	0xa7, 0xcf, 0x80, 0x3f, 0x85, 0x6e, 0x3e, 0xa4, 0xd8, 0x7c, 0x36, 0x46, 0x51, 0xb0, 0xc7, 0x2a,
	0x5f, 0x18, 0x1d, 0xe9, 0x43, 0x63, 0x4c, 0x53, 0xca, 0x22, 0x4b, 0x1b, 0x3f, 0x2c, 0x44, 0xfd,
	0xc6, 0xd1, 0x1b, 0x63, 0xa8, 0xdb, 0xb6, 0xb6, 0x52, 0xf0, 0x2d, 0x1c, 0xac, 0x0e, 0xa7, 0x7b,
	0x1d, 0x76, 0x95, 0x8c, 0xe7, 0x24, 0x73, 0xf1, 0x9f, 0x0f, 0x6d, 0x9d, 0xcc, 0xaf, 0x28, 0xde,
	0x26, 0x11, 0x92, 0x6b, 0xe8, 0x14, 0x6b, 0x44, 0xab, 0xc9, 0x71, 0xf5, 0x9c, 0x1b, 0x56, 0xcc,
	0xf0, 0x68, 0xdd, 0x9c, 0xd7, 0xfc, 0x0a, 0x5a, 0xe6, 0x11, 0x0c, 0xc6, 0x70, 0xd5, 0xc9, 0xdd,
	0x24, 0xc3, 0x47, 0x1b, 0x6d, 0x39, 0xca, 0x1d, 0xf4, 0x56, 0x33, 0x21, 0x8f, 0x2b, 0xf7, 0x8d,
	0x03, 0x78, 0x78, 0xbc, 0xcd, 0xc1, 0x16, 0xe1, 0x06, 0xba, 0x66, 0x02, 0x97, 0x80, 0x5f, 0x56,
	0xfe, 0x9b, 0x46, 0xf4, 0xb6, 0x04, 0x2f, 0xde, 0xfb, 0x40, 0x1c, 0x7e, 0x17, 0xe5, 0x7b, 0x0d,
	0x83, 0x4b, 0x81, 0x54, 0x61, 0xb1, 0x99, 0x1c, 0x1f, 0x32, 0x58, 0x6b, 0x8d, 0x6a, 0x71, 0x0d,
	0x3f, 0xa5, 0x6b, 0xc8, 0x2b, 0x38, 0xca, 0xc1, 0xf5, 0x26, 0x75, 0x91, 0x9d, 0x28, 0xdd, 0x2d,
	0xfb, 0x69, 0xb0, 0x7f, 0xc0, 0xe0, 0x06, 0xd5, 0x8f, 0x69, 0xea, 0xb8, 0xc8, 0x10, 0x23, 0x2e,
	0x62, 0x49, 0xfa, 0x15, 0xc2, 0xea, 0x4e, 0x18, 0x7e, 0xb3, 0x11, 0xfb, 0xc3, 0x89, 0xf2, 0xac,
	0xf5, 0x7b, 0xe3, 0xfc, 0xa9, 0xf9, 0xcb, 0x32, 0xae, 0x9b, 0x9f, 0x1f, 0xfe, 0x0f, 0x00, 0x00,
	0xff, 0xff, 0xf1, 0x79, 0xb9, 0x52, 0xd1, 0x08, 0x00, 0x00,
}
